### ISSUE TITLE
Precipitation field is causing a JSON decoding error when raining

### ISSUE THREAD

**Issue by vascocosta** [jt-rose/openweather_sdk#1]
I'm getting this decoding error when calling openweather.one_call.call() for a location where precipitation is greater than zero:

`error decoding response body: invalid type: floating point `0.1136`, expected u64 at line 1 column 2017`

It looks like declaring the precipitation field of Minutely as f64 instead of u64 could solve the issue.

**Comment by vascocosta** [comment]
Just tried a simple fix and submitted a pull request.

**Comment by jt-rose** [comment]
merged pull request - thanks for the help!
