### ISSUE TITLE
implementing a `current()`  method that uses OpenWeahter's current weather API (not one-call)

### ISSUE THREAD

**Issue by rakurtz** [jt-rose/openweather_sdk#4]
Hey JT,

first of all: great work! Thanks a lot. I noticed that your SDK doesn't allow to retrieve the current weather without using the one-call API of OpenWeather.

I would like to add a method (like `openweather.current()` or so) that uses the API described here: [https://openweathermap.org/current]( https://openweathermap.org/current).

Reason: one call API requires a different subscription.

What do you think about that? Would that fit into your SDK?

**Comment by jt-rose** [comment]
Looks good! Thanks for submitting a PR - I just approved it and pushed a new version to crates.io. 

I went ahead and removed the example-json section for now, since that info can be found on the openweather site.

Thanks again!

**Comment by rakurtz** [comment]
Hey Jeff,

thanks for merging and also thanks for tidying up some leftovers and typos..

Actually this was my first ever contribution to the open source world 😀😀😀😀

So even this is just a small add, for me it’s quite a thing :)

Best
Martin

**Comment by jt-rose** [comment]
That's great! Every little bit helps, and I appreciate the contribution!
